require "prototypes.spiderling"
require "prototypes.equipment-grid"
require "prototypes.custom-input"
require "prototypes.spidertron-remote"
require "prototypes.technology"
require "prototypes.style"
require "prototypes.sprite"
sp_data_stage = "data"
require "prototypes.nullius"
require "prototypes.space-exploration"
require "prototypes.signal"